version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  server:
    container_name: server
    build: .
    restart: on-failure
    env_file:
      - .env
    environment:
      - RELEASE_MODE=release
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
  frontend:
    container_name: frontend
    build: ../rlld-frontend/.
    restart: on-failure
    env_file:
      - ../rlld-frontend/.env
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server
volumes:
  db:
    driver: local

networks:
  elk:
