version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  server:
    container_name: server
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
volumes:
  db:
    driver: local
